from enum import StrEnum


class RuntimeErrorCode(StrEnum):
    """Stable runtime error codes shared across execution stages."""

    CONFIGURATION_ERROR = "configuration_error"
    DOCTOR_FAILED = "doctor_failed"
    AUTHENTICATION_ERROR = "authentication_error"
    REQUEST_SUBMIT_ERROR = "request_submit_error"
    POLL_TIMEOUT = "poll_timeout"
    NETWORK_CONNECT_TIMEOUT = "network_connect_timeout"
    NETWORK_SSL_ERROR = "network_ssl_error"
    PAYLOAD_PARSE_ERROR = "payload_parse_error"
    WORKBOOK_CAPABILITY_ERROR = "workbook_capability_error"
    WORKBOOK_SIZE_GUARDRAIL_TRIGGERED = "workbook_size_guardrail_triggered"
    WORKBOOK_WRITER_ERROR = "workbook_writer_error"
    WORKBOOK_TEMPLATE_MISSING = "workbook_template_missing"
    WORKBOOK_SHEET_MISSING = "workbook_sheet_missing"
    WORKBOOK_BLOCK_INVALID = "workbook_block_invalid"
    WORKBOOK_RANGE_DETECTION_FAILED = "workbook_range_detection_failed"
    WORKBOOK_FORMULA_SEED_MISSING = "workbook_formula_seed_missing"
    WORKBOOK_FORMULA_FILL_INCOMPLETE = "workbook_formula_fill_incomplete"
    WORKBOOK_CALCULATION_ERROR = "workbook_calculation_error"
    WORKBOOK_OUTPUT_READ_ERROR = "workbook_output_read_error"
    PUBLISH_AUTH_ERROR = "publish_auth_error"
    PUBLISH_RATE_LIMIT_ERROR = "publish_rate_limit_error"
    PUBLISH_TARGET_MISSING = "publish_target_missing"
    PUBLISH_RANGE_INVALID = "publish_range_invalid"
    PUBLISH_SOURCE_READ_ERROR = "publish_source_read_error"
    PUBLISH_WRITE_ERROR = "publish_write_error"
    PUBLISH_APPEND_RERUN_BLOCKED = "publish_append_rerun_blocked"
